apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: nginx
data:
  default.conf: |
    server {
        listen 80;
        location / {
            proxy_pass http://frontend-service:80;
        }
    }
